blank_issues_enabled: false

issue_templates:
  - name: ğŸ› Bug Report
    description: ë²„ê·¸ ë¦¬í¬íŠ¸ ì´ìŠˆ í…œí”Œë¦¿
    file: bug_report.md

  - name: âœ¨ Feature Request
    description: ê¸°ëŠ¥ ì¶”ê°€ ì´ìŠˆ í…œí”Œë¦¿
    file: feature_request.md

  - name: â™»ï¸ Refactor
    description: ë¦¬íŒ©í† ë§ ê´€ë ¨ ì´ìŠˆ í…œí”Œë¦¿
    file: refactor.md

  - name: â“ question
    description: ë…¼ì˜/ì§ˆë¬¸ ì´ìŠˆ í…œí”Œë¦¿
    file: question.md